#!/usr/bin/env node
// One prompt per ready pair for a model comparator, who sees only the two pages' screenshots, as A and B:
//   node tools/bench/comparator-prompts.mjs <round-dir>
// Writes <round>/comparator-prompts.json. Give each prompt to a fresh agent with no other context and no skills; it
// writes <round>/<eval>/pairs/pair-<n>/stage1.json, which record-round.mjs unblinds with the keys in pairs.json.
// The comparators are Claude models like the builders, so their taste is not independent of the builds; a person's
// blind judgement (judge-page.mjs) is the arbiter for beauty.
import fs from 'node:fs';
import path from 'node:path';
import { evalOfDir, loadEvals, parseArgs, readJson, usage, writeJson } from './lib.mjs';

// How each build eval's pages are named, and what a generic version of them would be.
const META = {
  'build-en-repair-cafe': { kind: 'websites', label: 'Site', distinct: 'specific to this repair cafe, or a generic template that any small organisation could swap its name into' },
  'build-zh-calligraphy-signup': { kind: 'web pages', label: 'Page', distinct: 'specific to a calligraphy class at a university for older people, or a generic template', chinese: true },
  'build-en-food-bank-tool': { kind: 'web tools', label: 'Tool', distinct: 'specific to this food bank front desk, or a generic admin template that any inventory app could swap its name into' },
  'build-zh-watch-repair': { kind: 'web pages', label: 'Page', distinct: 'specific to this three-generation watch repair shop in the old town, or a generic template', chinese: true },
};
const fallback = (name) => ({ kind: 'web pages', label: 'Page', distinct: 'specific to this request, or a generic template that could carry any name', chinese: /-zh-/.test(name) });

const { pos, opts } = parseArgs(process.argv.slice(2));
const round = pos[0] && path.resolve(pos[0]);
if (!round || !fs.existsSync(path.join(round, 'pairs.json'))) usage('usage: node tools/bench/comparator-prompts.mjs <round-dir>   (run make-pairs.mjs first)', opts.help);
const evals = loadEvals();
const prompts = [];
for (const p of readJson(path.join(round, 'pairs.json')).filter((x) => x.ready)) {
  const e = evalOfDir(p.eval, evals);
  if (!e) throw new Error(`${p.eval} is not in evals/evals.json`);
  const m = META[e.name] || fallback(e.name);
  const base = path.join(round, p.eval, 'pairs', `pair-${p.pair}`);
  const output = path.join(base, 'stage1.json');
  const prompt = `You are an experienced product designer judging two ${m.kind} built for the same request, the way a first-time visitor would see them.${m.chinese ? ' You read Chinese.' : ''}

You do not know how either was made, and it does not matter. Judge only from the screenshots. Do not read any other files on this machine and do not use the Skill tool.

The request the builders received:
"${e.prompt}"

The two ${m.kind} (full-page screenshots at 375 px and 1280 px wide):
- ${m.label} A: ${path.join(base, 'A/screens')}
- ${m.label} B: ${path.join(base, 'B/screens')}

1. Look carefully at every screenshot of both with the Read tool.
2. Score each from 1 (poor) to 5 (excellent) on:
   - visual quality: typography, spacing, hierarchy, colour, polish. Would a professional designer be proud of it?
   - distinctiveness: ${m.distinct}? Would a visitor suspect it was generated by AI?
3. Give two verdicts, each A, B or tie, with one sentence of reason: "more_beautiful" and "less_generic" (less like a generic or AI-made template). Be decisive: ties should be rare.

Write the result as JSON to ${output}, with this shape:
{"scores": {"A": {"visual": n, "distinct": n}, "B": {"visual": n, "distinct": n}}, "more_beautiful": {"winner": "A|B|tie", "reason": "…"}, "less_generic": {"winner": "A|B|tie", "reason": "…"}}

Reply with at most 3 lines: the two verdicts.`;
  prompts.push({ id: `${p.eval}#${p.pair}`, description: `Blind comparison: ${e.name}, pair ${p.pair}`, output, prompt });
}
writeJson(path.join(round, 'comparator-prompts.json'), prompts);
console.log(`${prompts.length} prompt(s) in ${path.join(round, 'comparator-prompts.json')}`);
