#!/usr/bin/env node
// Generate the Claude Code plugin's agents/<role>.md from the portable role prompts in
// skills/ui-evaluator/references/evaluators/. The role prompts stay the single source; other agents (Codex, Cursor,
// Gemini CLI) read them directly. `--check` exits 1 when agents/ is out of date.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'skills/ui-evaluator/references/evaluators');
const OUT = path.join(ROOT, 'agents');

// One line each: when the lead spawns the role. Plugin agents are namespaced as ui-evaluator:<role>.
const ROLES = {
  'heuristic-evaluator': {
    description: 'Isolated heuristic evaluator for a UI-Evaluator audit. Spawn one per packet built by `uie packet --role heuristic-evaluator`; it inspects the rendered UI against H1–H10 through its packet and `uie probe` only, and writes candidate findings without severity.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
  'walkthrough-evaluator': {
    description: 'Isolated cognitive-walkthrough evaluator for a UI-Evaluator audit. Spawn one per persona-journey packet from `uie packet --role walkthrough-evaluator`; it answers the four walkthrough questions at every step and records failure stories.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
  'design-critic': {
    description: 'Isolated design critic for a UI-Evaluator design panel. Spawn one per critic packet from `uie packet --role design-critic`; it judges specificity, appeal, brand fit and craft from screenshots, writes its verdicts before it may read detector output, and never sees the builder\'s rationale.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
  'accessibility-auditor': {
    description: 'Accessibility auditor for a UI-Evaluator audit. Spawn with the packet from `uie packet --role accessibility-auditor`; it resolves axe incomplete results, judges the agent-judged WCAG 2.2 AA criteria with evidence and lists what needs a human.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
  'code-reviewer': {
    description: 'White-box code reviewer for UI-Evaluator. Spawn with `uie packet --role code-reviewer --phase review` to find source-level UI defects, or `--phase locate` to map confirmed findings to file:line and estimate ease of fix. It never judges the UX.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
  'finding-verifier': {
    description: 'Finding verifier for UI-Evaluator. Spawn with the packet from `uie packet --role finding-verifier`; it re-checks each candidate against the rendered UI through the verification chain and confirms, rejects or splits it.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
  'severity-rater': {
    description: 'Blind severity rater for UI-Evaluator. Spawn three or more, one per packet from `uie packet --role severity-rater`; each rates frequency, impact and persistence and a 0–4 severity for anonymised findings, or votes not a problem or trade-off.',
    tools: 'Read, Bash, Write',
  },
  'fix-reviewer': {
    description: 'Fresh fix reviewer for the UI-Evaluator verify workflow. Spawn with the packet from `uie packet --role fix-reviewer`; from before-and-after evidence only it scores each claimed fix confirmed_fixed, partially_fixed or not_fixed and names up to three regressions.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
  'direction-designer': {
    description: 'Direction designer for the UI-Evaluator direct workflow. Spawn with the packet from `uie packet --role direction-designer --directions`; it develops one dealt direction into tokens, a first viewport and a contract, without seeing the other directions.',
    tools: 'Read, Glob, Grep, Bash, Write',
  },
};

const PREFACE = (role) => `<!-- Generated by tools/sync-agents.mjs from skills/ui-evaluator/references/evaluators/${role}.md. Edit that file, then run the tool. -->

\`<skill-dir>\` below is the skill directory named in your packet's README.md (in this plugin: \`\${CLAUDE_PLUGIN_ROOT}/skills/ui-evaluator\`). Start by reading that README; it gives your agent id, your output path and the exact command for \`uie\`.

`;

export function render(role, body) {
  const meta = ROLES[role];
  if (!meta) throw new Error(`no agent metadata for role "${role}" in tools/sync-agents.mjs`);
  const desc = meta.description.replace(/"/g, '\\"');
  return `---\nname: ${role}\ndescription: "${desc}"\ntools: ${meta.tools}\nmodel: inherit\n---\n\n${PREFACE(role)}${body.trim()}\n`;
}

function main() {
  const check = process.argv.includes('--check');
  const roles = fs.readdirSync(SRC).filter((f) => f.endsWith('.md')).map((f) => f.replace(/\.md$/, '')).sort();
  const missingMeta = roles.filter((r) => !ROLES[r]);
  if (missingMeta.length) {
    console.error(`role prompt(s) without agent metadata: ${missingMeta.join(', ')}`);
    return 1;
  }
  if (!check) fs.mkdirSync(OUT, { recursive: true });
  const stale = [];
  for (const role of roles) {
    const want = render(role, fs.readFileSync(path.join(SRC, `${role}.md`), 'utf8'));
    const file = path.join(OUT, `${role}.md`);
    const have = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (have === want) continue;
    if (check) stale.push(role);
    else fs.writeFileSync(file, want);
  }
  const extra = fs.existsSync(OUT) ? fs.readdirSync(OUT).filter((f) => f.endsWith('.md') && !roles.includes(f.replace(/\.md$/, ''))) : [];
  if (check) {
    if (stale.length || extra.length) {
      console.error(`agents/ is out of date: ${[...stale, ...extra.map((e) => `${e} (no source)`)].join(', ')}. Run node tools/sync-agents.mjs`);
      return 1;
    }
    console.log(`agents/: ${roles.length} agent(s) in sync`);
    return 0;
  }
  for (const e of extra) fs.rmSync(path.join(OUT, e));
  console.log(`agents/: wrote ${roles.length} agent file(s)${extra.length ? `; removed ${extra.join(', ')}` : ''}`);
  return 0;
}

if (import.meta.url === `file://${process.argv[1]}`) process.exitCode = main();
